name: oneApi-linux
description: Install Intel oneAPI
inputs:
  LINUX_HPCKIT_URL:
    description: 'URL to download the Intel oneAPI HPC Toolkit for Linux'
    default: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/0884ef13-20f3-41d3-baa2-362fc31de8eb/intel-oneapi-hpc-toolkit-2025.0.0.825_offline.sh
    required: false
  LINUX_COMPONENTS: 
    description: 'Components to install for Intel oneAPI C++ compiler for Linux'
    default: intel-oneapi-dpcpp-cpp-compiler
    required: false
  
runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
    clean: false
  - name: Check cache for Intel oneAPI
    id: cache-install
    uses: actions/cache@v4
    with:
      path: |
          /opt/intel/oneapi
      key: install-${{ inputs.LINUX_HPCKIT_URL }}-${{ inputs.LINUX_COMPONENTS }}-${{ hashFiles('${{ github.action_path }}/action.yml') }}
  
  - name: Install Intel oneAPI
    if: steps.cache-install.outputs.cache-hit != 'true'
    run: |
      scripts/installOneApi.sh ${{ inputs.LINUX_HPCKIT_URL }}  ${{ inputs.LINUX_COMPONENTS }}
    shell: bash
    working-directory: ${{ github.action_path }}

  - name: Make oneapi available
    run: |
      scripts/updateEnvironment.sh
    shell: bash
    working-directory: ${{ github.action_path }}

  

  